name: Android Pull Request Unit Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
      actions: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: "**/test-results/**/*.xml"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with: 
          commit: ${{github.event.pull_request.head.sha}}
          files: "**/test-results/**/*.xml"
